import 'package:appflowy/plugins/resource_surface/engine_registry.dart';
import 'package:appflowy/plugins/resource_surface/resource_open_request.dart';
import 'package:flutter/material.dart';

/// Formats Open File Viewer is built for. [catchAll] also covers unknown types.
const openFileViewerSupportedExtensions = <String>{
  '3gp',
  'aac',
  'aiff',
  'avif',
  'avi',
  'bmp',
  'csv',
  'doc',
  'docm',
  'epub',
  'flac',
  'gif',
  'htm',
  'html',
  'ico',
  'jpeg',
  'jpg',
  'm4a',
  'm4v',
  'mkv',
  'mov',
  'mp3',
  'mp4',
  'odp',
  'ods',
  'odt',
  'ogg',
  'pdf',
  'png',
  'ppt',
  'pptx',
  'rtf',
  'svg',
  'tif',
  'tiff',
  'tsv',
  'url',
  'wav',
  'webp',
  'webm',
  'xls',
  'xlsx',
  'xps',
  'zip',
};

const openFileViewerEngineSpec = MuseResourceEngineSpec(
  engine: MuseLocalEngine.openFileViewer,
  id: 'muse.open-file-viewer',
  label: 'Open File Viewer',
  icon: Icons.visibility_outlined,
  extensions: openFileViewerSupportedExtensions,
  catchAll: true,
  priority: 10,
);
