#!/usr/bin/env python3
"""Stamp brand/config.yaml into Dart, i18n, and native project files.

Edit frontend/client/brand/config.yaml, then run this script.
Pack/install scripts load the YAML themselves and do not need a stamp.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR / "lib"))

from brand_config import BrandConfig, load_brand_config  # noqa: E402

CLIENT = SCRIPT_DIR.parent
FLUTTER = CLIENT / "frontend" / "appflowy_flutter"
FRONTEND = CLIENT / "frontend"


def xcode_str(value: str) -> str:
    if re.search(r"[^A-Za-z0-9_.]", value):
        return f'"{value}"'
    return value


def replace_once(pattern: str, repl: str, text: str, path: Path, flags: int = 0) -> str:
    updated, count = re.subn(pattern, repl, text, count=1, flags=flags)
    if count != 1:
        raise ValueError(f"{path}: expected 1 match for {pattern!r}, got {count}")
    return updated


def sub_all(pattern: str, repl: str, text: str) -> str:
    return re.sub(pattern, repl, text)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")
    print(f"  wrote {path.relative_to(CLIENT)}")


def patch(path: Path, transform) -> None:
    original = path.read_text(encoding="utf-8")
    updated = transform(original)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
        try:
            shown = path.relative_to(CLIENT)
        except ValueError:
            shown = path
        print(f"  patched {shown}")


def dart_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def write_brand_values(brand: BrandConfig) -> None:
    legacy = ",\n    ".join(f"'{dart_escape(item)}'" for item in brand.legacy_display)
    write(
        FLUTTER / "lib" / "brand" / "brand_values.g.dart",
        f"""// Generated by frontend/client/scripts/apply-brand.py from brand/config.yaml.
// Do not edit by hand.

class BrandValues {{
  BrandValues._();

  static const productNameEn = '{dart_escape(brand.name_en)}';
  static const productNameZh = '{dart_escape(brand.name_zh)}';
  static const binaryWindows = '{dart_escape(brand.binary_windows)}';
  static const binaryLinux = '{dart_escape(brand.binary_linux)}';
  static const macosApp = '{dart_escape(brand.macos_app)}';
  static const dataDir = '{dart_escape(brand.data_dir)}';
  static const dataDirLinux = '{dart_escape(brand.data_dir_linux)}';
  static const artifactPrefix = '{dart_escape(brand.artifact_prefix)}';
  static const companyName = '{dart_escape(brand.company_name)}';
  static const legacyDisplayNames = <String>[
    {legacy}
  ];
}}
""",
    )


def write_android_strings(brand: BrandConfig) -> None:
    res = FLUTTER / "android" / "app" / "src" / "main" / "res"
    write(
        res / "values" / "strings.xml",
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<resources>\n"
        f'    <string name="app_name">{brand.name_en}</string>\n'
        "</resources>\n",
    )
    zh = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<resources>\n"
        f'    <string name="app_name">{brand.name_zh}</string>\n'
        "</resources>\n"
    )
    write(res / "values-zh" / "strings.xml", zh)
    write(res / "values-zh-rTW" / "strings.xml", zh)
    write(res / "values-zh-rCN" / "strings.xml", zh)


def write_infoplist_strings(brand: BrandConfig) -> None:
    zh = brand.name_zh
    hans = f'''CFBundleDisplayName = "{zh}";
CFBundleName = "{zh}";
NSCameraUsageDescription = "{zh}需要使用相机，以便把照片加入文档。";
NSMicrophoneUsageDescription = "{zh}需要使用麦克风，以便把语音转成草稿。音频只留在本机，不会自动发送。";
NSPhotoLibraryAddUsageDescription = "{zh}需要访问相册，以便把图片保存到相册。";
NSPhotoLibraryUsageDescription = "{zh}需要访问相册，以便把图片加入文档。";
NSSpeechRecognitionUsageDescription = "{zh}仅在填写草稿时使用语音识别。点发送后才会提交内容。";
'''
    hant = f'''CFBundleDisplayName = "{zh}";
CFBundleName = "{zh}";
NSCameraUsageDescription = "{zh}需要使用相機，以便把照片加入文件。";
NSMicrophoneUsageDescription = "{zh}需要使用麥克風，以便把語音轉成草稿。音訊只留在本機，不會自動傳送。";
NSPhotoLibraryAddUsageDescription = "{zh}需要取用相簿，以便把圖片儲存到相簿。";
NSPhotoLibraryUsageDescription = "{zh}需要取用相簿，以便把圖片加入文件。";
NSSpeechRecognitionUsageDescription = "{zh}僅在填寫草稿時使用語音辨識。點傳送後才會提交內容。";
'''
    write(FLUTTER / "ios" / "Runner" / "zh-Hans.lproj" / "InfoPlist.strings", hans)
    write(FLUTTER / "ios" / "Runner" / "zh-Hant.lproj" / "InfoPlist.strings", hant)
    mac = f'CFBundleDisplayName = "{zh}";\nCFBundleName = "{zh}";\n'
    write(FLUTTER / "macos" / "Runner" / "zh-Hans.lproj" / "InfoPlist.strings", mac)
    write(FLUTTER / "macos" / "Runner" / "zh-Hant.lproj" / "InfoPlist.strings", mac)


def replace_plist_key(text: str, key: str, value: str) -> str:
    return re.sub(
        rf"(<key>{re.escape(key)}</key>\s*<string>)[^<]*(</string>)",
        rf"\g<1>{value}\2",
        text,
        count=1,
    )


def rewrite_translation_value(value: str, new_name: str, brand: BrandConfig) -> str:
    names = [new_name, *brand.legacy_display]
    # Longest first so "OpenMuse AI" wins over "Muse".
    names = sorted(set(names), key=len, reverse=True)
    for old in names:
        if old == new_name:
            continue
        if re.search(r"[A-Za-z]", old):
            value = re.sub(rf"(?<![A-Za-z]){re.escape(old)}(?![A-Za-z])", new_name, value)
            value = value.replace(f"\\n{old}", f"\\n{new_name}")
        else:
            value = value.replace(old, new_name)
    return value


def stamp_translations(brand: BrandConfig) -> None:
    src = CLIENT / "frontend" / "resources" / "translations"
    dst = FLUTTER / "assets" / "translations"
    for path in sorted(src.glob("*.json")):
        name = brand.display_for_locale(path.stem)
        original = path.read_text(encoding="utf-8")
        raw = rewrite_translation_value(original, name, brand)
        raw, app_count = re.subn(
            r'"appName"\s*:\s*"[^"]*"',
            f'"appName": "{name}"',
            raw,
            count=1,
        )
        if raw != original:
            path.write_text(raw, encoding="utf-8")
            print(f"  patched translations/{path.name} → {name} (appName x{app_count})")
        dest = dst / path.name
        dest.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")


def stamp_native(brand: BrandConfig) -> None:
    en = brand.name_en
    company = brand.company_name
    win = brand.binary_windows
    linux = brand.binary_linux
    mac = brand.macos_app

    patch(
        FLUTTER / "windows" / "CMakeLists.txt",
        lambda t: re.sub(r'set\(BINARY_NAME "[^"]*"\)', f'set(BINARY_NAME "{win}")', t, count=1),
    )
    patch(
        FLUTTER / "linux" / "CMakeLists.txt",
        lambda t: re.sub(r'set\(BINARY_NAME "[^"]*"\)', f'set(BINARY_NAME "{linux}")', t, count=1),
    )
    patch(
        FRONTEND / "Makefile.toml",
        lambda t: re.sub(r'PRODUCT_NAME = "[^"]*"', f'PRODUCT_NAME = "{mac}"', t, count=1),
    )
    patch(
        FLUTTER / "macos" / "Runner" / "Configs" / "AppInfo.xcconfig",
        lambda t: re.sub(r"^PRODUCT_NAME = .*$", f"PRODUCT_NAME = {mac}", t, count=1, flags=re.M),
    )
    patch(
        FRONTEND / "scripts" / "white_label" / "white_label.sh",
        lambda t: re.sub(r'^APP_NAME="[^"]*"', f'APP_NAME="{en}"', t, count=1, flags=re.M),
    )

    def rc(text: str) -> str:
        text = re.sub(r'(VALUE "FileDescription", )"[^"]*"', rf'\1"{en}"', text, count=1)
        text = re.sub(r'(VALUE "InternalName", )"[^"]*"', rf'\1"{en}"', text, count=1)
        text = re.sub(r'(VALUE "OriginalFilename", )"[^"]*"', rf'\1"{brand.windows_exe}"', text, count=1)
        text = re.sub(r'(VALUE "ProductName", )"[^"]*"', rf'\1"{en}"', text, count=1)
        text = re.sub(r'(VALUE "CompanyName", )"[^"]*"', rf'\1"{company.lower()}"', text, count=1)
        return text

    patch(FLUTTER / "windows" / "runner" / "Runner.rc", rc)

    def cpp(text: str) -> str:
        text = re.sub(r'FindWindowA\(NULL, "[^"]+"\)', f'FindWindowA(NULL, "{en}")', text)
        text = re.sub(r'SendAppLinkToInstance\(L"[^"]+"\)', f'SendAppLinkToInstance(L"{en}")', text)
        text = re.sub(r'Create\(L"[^"]+"', f'Create(L"{en}"', text, count=1)
        return text

    patch(FLUTTER / "windows" / "runner" / "main.cpp", cpp)
    patch(
        FLUTTER / "linux" / "my_application.cc",
        lambda t: re.sub(
            r'gtk_window_set_title\(window, "[^"]+"\)',
            f'gtk_window_set_title(window, "{en}")',
            t,
            count=1,
        ),
    )

    for pbx in (
        FLUTTER / "ios" / "Runner.xcodeproj" / "project.pbxproj",
        FLUTTER / "macos" / "Runner.xcodeproj" / "project.pbxproj",
    ):
        patch(
            pbx,
            lambda t: re.sub(
                r"INFOPLIST_KEY_CFBundleDisplayName = [^;]+;",
                f"INFOPLIST_KEY_CFBundleDisplayName = {xcode_str(en)};",
                t,
            ),
        )
    patch(
        FLUTTER / "macos" / "Runner.xcodeproj" / "project.pbxproj",
        lambda t: re.sub(
            r"path = [^;\s]+\.app;",
            f"path = {xcode_str(brand.macos_app_bundle)};",
            t,
        ),
    )

    def macos_product(text: str) -> str:
        def repl(match: re.Match[str]) -> str:
            current = match.group(0)
            if "TARGET_NAME" in current:
                return current
            return match.group(1) + xcode_str(mac) + ";"

        return re.sub(
            r"(PRODUCT_NAME = )(?:\"[^\"]+\"|[A-Za-z0-9_.]+);",
            repl,
            text,
        )

    patch(FLUTTER / "macos" / "Runner.xcodeproj" / "project.pbxproj", macos_product)

    def ios_plist(text: str) -> str:
        text = replace_plist_key(text, "CFBundleName", en)
        text = replace_plist_key(text, "CFBundleDisplayName", en)
        en_usage = {
            "NSCameraUsageDescription": f"{en} needs access to your camera to let you add images to your documents from the camera.",
            "NSMicrophoneUsageDescription": f"{en} needs the microphone so DSH can turn speech into draft text. Audio stays on the device and is never sent automatically.",
            "NSPhotoLibraryAddUsageDescription": f"{en} needs access to your photos to let you add images to your photo library.",
            "NSPhotoLibraryUsageDescription": f"{en} needs access to your photos to let you add images to your documents.",
            "NSSpeechRecognitionUsageDescription": f"{en} uses speech recognition only to fill the DSH draft. Nothing is submitted until you tap send.",
        }
        for key, value in en_usage.items():
            text = replace_plist_key(text, key, value)
        return text

    patch(FLUTTER / "ios" / "Runner" / "Info.plist", ios_plist)

    iss = FRONTEND / "scripts" / "windows_installer" / "inno_setup_config.iss"
    exe = brand.windows_exe
    portable = brand.binary_windows
    write(
        iss,
        f"""[Setup]
AppName={en}
AppVersion={{#AppVersion}}
AppPublisher={company}
WizardStyle=modern
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=lowest
DefaultDirName={{localappdata}}\\Programs\\{portable}
DefaultGroupName={en}
UninstallDisplayIcon={{app}}\\{exe}
UninstallDisplayName={en}
VersionInfoVersion={{#AppVersion}}
UsePreviousAppDir=no
#ifexist "flowy_logo.ico"
SetupIconFile=flowy_logo.ico
#endif

[Files]
Source: "{portable}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{userdesktop}}\\{en}"; Filename: "{{app}}\\{exe}"
Name: "{{group}}\\{en}"; Filename: "{{app}}\\{exe}"

[Run]
Filename: "{{app}}\\{exe}"; Description: "Launch {en}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\\Classes\\dsh-office"; ValueType: "string"; ValueData: "URL:Custom Protocol"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\\Classes\\dsh-office"; ValueType: "string"; ValueName: "URL Protocol"; ValueData: ""
Root: HKCU; Subkey: "Software\\Classes\\dsh-office\\DefaultIcon"; ValueType: "string"; ValueData: "{{app}}\\{exe},0"
Root: HKCU; Subkey: "Software\\Classes\\dsh-office\\shell\\open\\command"; ValueType: "string"; ValueData: \"\"\"{{app}}\\{exe}\"\" \"\"%1\"\"\"
Root: HKCU; Subkey: "Software\\Classes\\openmuse"; ValueType: "string"; ValueData: "URL:{en}"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\\Classes\\openmuse"; ValueType: "string"; ValueName: "URL Protocol"; ValueData: ""
Root: HKCU; Subkey: "Software\\Classes\\openmuse\\DefaultIcon"; ValueType: "string"; ValueData: "{{app}}\\{exe},0"
Root: HKCU; Subkey: "Software\\Classes\\openmuse\\shell\\open\\command"; ValueType: "string"; ValueData: \"\"\"{{app}}\\{exe}\"\" \"\"%1\"\"\"
""",
    )

    def linux_yaml(text: str) -> str:
        text = re.sub(r"^display_name:.*$", f"display_name: {en}", text, count=1, flags=re.M)
        text = re.sub(r"^generic_name:.*$", f"generic_name: {en}", text, count=1, flags=re.M)
        text = re.sub(r"^  - .+\n", f"  - {en}\n", text, count=1, flags=re.M)
        return text

    patch(FLUTTER / "linux" / "packaging" / "deb" / "make_config.yaml", linux_yaml)
    patch(FLUTTER / "linux" / "packaging" / "rpm" / "make_config.yaml", linux_yaml)

    patch(
        FLUTTER / "pubspec.yaml",
        lambda t: re.sub(
            r"^description: .*$",
            f"description: {en} is an AI-native office suite. Work locally, keep your",
            t,
            count=1,
            flags=re.M,
        ),
    )

    dockerfile = FRONTEND / "scripts" / "docker-buildfiles" / "Dockerfile"
    if dockerfile.is_file():
        def docker(text: str) -> str:
            text = re.sub(r"test -e \./[A-Za-z0-9_-]+", f"test -e ./{linux}", text)
            text = re.sub(r"file \./[A-Za-z0-9_-]+", f"file ./{linux}", text)
            text = re.sub(r'CMD \["\./[^"]+"\]', f'CMD ["./{linux}"]', text)
            return text

        patch(dockerfile, docker)

    installer = CLIENT / "install.sh"
    if installer.is_file():
        patch(
            installer,
            lambda t: re.sub(r"^BINARY=.*$", f"BINARY={linux}", t, count=1, flags=re.M),
        )


def stamp_template_and_catalog(brand: BrandConfig) -> None:
    en = brand.name_en
    prefix = brand.artifact_prefix
    readme = FLUTTER / "assets" / "template" / "readme.json"
    if readme.is_file():
        patch(
            readme,
            lambda t: re.sub(
                r"Welcome to [^!]+!",
                f"Welcome to {en}!",
                t,
            ).replace("Like Muse?", f"Like {en}?").replace("Like OpenMuse?", f"Like {en}?"),
        )
    catalog = Path("/Users/mac/src/openmuse-io/Muse-WebSite/lib/config/downloads.catalog.json")
    if catalog.is_file():
        def cat(text: str) -> str:
            data = json.loads(text)
            version = data.get("version", "0.11.4")
            data["windows"] = f"/downloads/windows/{prefix}-{version}-windows-x64.zip"
            mac = data.get("macos") or {}
            mac["intel"] = f"/downloads/macos/{prefix}-{version}-macos-universal.zip"
            mac["universal"] = f"/downloads/macos/{prefix}-{version}-macos-universal.zip"
            data["macos"] = mac
            data["ios"] = f"/downloads/ios/{prefix}-{version}-ios-arm64.ipa"
            data["android"] = f"/downloads/android/{prefix}-{version}-android-arm64.apk"
            return json.dumps(data, indent=2) + "\n"

        patch(catalog, cat)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=None)
    args = parser.parse_args()
    brand = load_brand_config(args.config)
    print(f"Applying {brand.name_en} / {brand.name_zh}")
    write_brand_values(brand)
    write_android_strings(brand)
    write_infoplist_strings(brand)
    stamp_native(brand)
    stamp_translations(brand)
    stamp_template_and_catalog(brand)
    print("Done. Rebuild the client for native names to take effect.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
